### ISSUE TITLE
After upgrade to 1.8, cfscrape does not work when executed from another script

### ISSUE THREAD

**Issue by brandonkay** [Anorov/cloudflare-scrape#99] opened 2017-04-12 13:57 UTC
Hello,

Thank you for this script, however after upgrading to 1.8, the scrape does not seem to be working. It works fine when I run my python script from the command line, but when I shell_exec from my php script, it does not work. I don't see any errors so I am not sure where the hangup is, but I downgraded back to 1.7 and it seems to work fine. Hope this helps you narrow down the issue.

**Comment by Xonshiz** [comment] 2017-04-12 16:11
Possible duplicate of [Newer versions will not allow execution from php](https://github.com/Anorov/cloudflare-scrape/issues/98).

You need "NodeJS" for the versions 1.8. Try that

**Comment by Anorov** [comment] 2017-04-17 05:08
Please see @Xonshiz's answer.

Please also don't open issues without including error and traceback information.

**Closed by Anorov** 2017-04-17 05:08 UTC
