### ISSUE TITLE
Could not collect tokens

### ISSUE THREAD

**Issue by Redkin77** [Anorov/cloudflare-scrape#251] opened 2019-05-18 15:40 UTC
Before creating an issue, first upgrade cfscrape with `pip install -U cfscrape` and see if you're still experiencing the problem.

## Version number

Run `pip show cfscrape` and paste the output below:

```
Name: cfscrape
Version: 2.0.5
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
Home-page: https://github.com/Anorov/cloudflare-scrape
Author: Anorov
Author-email: anorov.vorona@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python3.6/dist-packages
Requires: requests
Required-by: 

```

## Code snippet experiencing the issue

```
import cfscrape
import sys
import subprocess
import re
import signal

def signal_handler(signum, frame):
    raise Exception("Timed out!")

url = sys.argv[1]


headers = {'Content-Type': 'text/html; charset=utf-8', 'user-agent': line2, 'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'q=0.9,ru;q=0.7', 'cache-control': 'max-age=0', 'upgrade-insecure-requests': '1', 'cookie': line1}

scraper = cfscrape.create_scraper(delay=15) 



signal.signal(signal.SIGALRM, signal_handler)
signal.alarm(15)  
output = scraper.get(url,  headers=headers).content

```

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

```
ERROR:root:'https://olimpkz.com/betting' returned an error. Could not collect tokens.

```

## URL of the Cloudflare-protected page

https://olimpkz.com/betting

## URL of Pastebin/Gist with HTML source of protected page

[LINK GOES HERE]

**Comment by pro-src** [comment] 2019-05-18 17:21
Hi @Redkin77,

Your code snippet mostly works fine for https://olimpkz.com/betting. There are a few problems with it though.

* Multiple challenges may be solved before the request returns aka the timeout may vary. 
* Cloudflare's BIC scrutinizes the headers so it's best to let cfscrape handle that for you.
* The Content-Type header is a response header, not a request header.
* At minimum, I would wait 5 seconds for each challenge and wait for at least 3 possible challenges
* Probably should stick with the default delay unless experiencing problems, ~4 seconds

If you need to specify headers, you may but please eliminate custom headers as being the cause of your problem.

```py
import cfscrape
import sys
import subprocess
import re
import signal

def signal_handler(signum, frame):
    raise Exception("Timed out!")

url = 'https://olimpkz.com/betting'

# headers = {'Content-Type': 'text/html; charset=utf-8', 'user-agent': line2, 'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'q=0.9,ru;q=0.7', 'cache-control': 'max-age=0', 'upgrade-insecure-requests': '1', 'cookie': line1}

scraper = cfscrape.create_scraper() 

signal.signal(signal.SIGALRM, signal_handler)
signal.alarm(15)  
output = scraper.get(url).content
```

**Comment by pro-src** [comment] 2019-05-18 19:41
Also, the error message that you've reported could not possibly be generated using that code snippet. That particular error message can only occur if you use `get_cookie_string` or `get_tokens`. I've tested `get_tokens` for the URL on both python 2 and 3, no problems.

Since I don't believe this to be a problem with the library, I'm going to close it out.

**Closed by pro-src** 2019-05-18 19:41 UTC
Labels: bug, unconfirmed
