### ISSUE TITLE
Possible Proxy Bug

### ISSUE THREAD

**Issue by bezkos** [Anorov/cloudflare-scrape#164] opened 2018-07-10 05:56 UTC
I used below code to use cloudflare-scrape with authorized proxy

``
proxies = {"http": "http://test:123@200.30.20.40:8080"}

tokens, user_agent = cfscrape.get_tokens("http://somesite.com", proxies=proxies)
``
I wanted to be 100% sure that cloudflare-scrape use proxy ip instead of server ip and i pass wrong username-password. Cloudflare-scrape keep working through its phases even if i passed wrong credentials. So I think there is a bug here and clouflare-scrape never use proxy dict even if we provide it..

**Comment by Anorov** [comment] 2018-07-24 07:38
Do you still have this issue if you also set an `"https"` key in the `proxies` dict?

Like so:

```python
proxies = {
    "http": "http://test:123@200.30.20.40:8080",
    "https": "http://test:123@200.30.20.40:8080"
}
```

**Comment by bezkos** [comment] 2018-07-24 10:07
I tried to test with https. 
Unfortunately site dont use anymore cloudflare so after 1st phase with 200 response, it starts download fine.
I gave wrong credentials to proxy dict and i got Proxy Authentication Required that i guess is fine.
So if there is a bug here, it is for sure after 1st phase of clouflare-scrape.

**Comment by pro-src** [comment] 2019-05-11 17:47
@bezkos I guess the problem could have been that the credentials weren't been validated?
If you make a request to http://httpbin.org/get it will respond with your IP address. I would perform the test with and without the `proxies` argument to see if the IP is changing. If the `proxies` argument is being ignored (It isn't for me) then it would be a bug with the `requests` library.

If you can reproduce the problem for `requests`, I'd open an issue at https://github.com/kennethreitz/requests

```py
import requests
proxies = {"http": "http://test:123@200.30.20.40:8080"}

print(requests.get("http://httpbin.org/get", proxies=proxies).content)
```

**Comment by pro-src** [comment] 2019-05-13 12:29
I'm unable to reproduce as of date. If it was reproducible it would more than likely be a `requests` bug, so I'm going to close it. If I missed something, please request it to be reopened.

**Closed by pro-src** 2019-05-13 12:29 UTC
Labels: bug
