### ISSUE TITLE
cfscrape cannot solve captchas

### ISSUE THREAD

**Issue by bajburtskii** [Anorov/cloudflare-scrape#268] opened 2019-06-21 10:08 UTC
Hello! Is there any chance that somebody can help me?
The server is a fresh instance set up specially for the test. Ubuntu 19.04 with nodejs installed.
None of the python versions(2.7, 3.7) seems to solve the issue.
Thanks for any help!
Just in case I've attached the output from terminal
![Selection_002](https://user-images.githubusercontent.com/1996929/59915505-76d6cc00-9425-11e9-9101-e5999b70e925.png)

## Version number

Run `pip show cfscrape` and paste the output below:
Name: cfscrape
Version: 2.0.7
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
Home-page: https://github.com/Anorov/cloudflare-scrape
Author: Anorov
Author-email: anorov.vorona@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python2.7/dist-packages
Requires: requests
Required-by:

## Code snippet experiencing the issue
import cfscrape

scraper = cfscrape.create_scraper() 
print scraper.get("https://www.enotes.com/topics/alpha/").content 

## Complete exception and traceback

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    print (scraper.get("https://www.enotes.com/topics/alpha/").content)  # => "<!DOCTYPE html><html><head>..."
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 124, in request
    self.handle_captcha_challenge(resp, url)
  File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 147, in handle_captcha_challenge
    raise CloudflareCaptchaError(error, response=resp)
cfscrape.CloudflareCaptchaError: Cloudflare captcha challenge presented for www.enotes.com (cfscrape cannot solve captchas)

## URL of the Cloudflare-protected page

https://www.enotes.com/topics/alpha/

## URL of Pastebin/Gist with HTML source of protected page

https://pastebin.com/CXKapc0B

**Comment by Bloumbs** [comment] 2019-06-24 23:12
**"OpenSSL version is lower than 1.1.1."**
I am also having this issue with my scraper set up in pretty much the same way:
```
import cfscrape

scraper = cfscrape.create_scraper()
data = scraper.get(link).content
soup = BeautifulSoup(data, 'html.parser')

etc....
```

Except in my error, after the message:
"Cloudflare captcha challenge presented for .... (cfscrape cannot solve captchas)."

I get the message:
"Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python."

I don't know what this has to do with the issue, if anything. Just pointing it out.

**Comment by pro-src** [comment] 2019-06-25 10:40
Cloudflare finds outdated/insecure ciphers when checking your SSL/TLS connection and sends a CAPTCHA in response to it.

The message is pretty clear. There are many duplicate issues with this message of which I have responded to in more detail. There are workarounds, etc.

**Comment by bajburtskii** [comment] 2019-06-25 10:41
anything regarding the initial issue? Thanks

**Comment by pro-src** [comment] 2019-06-25 11:39
Sorry @bajburtskii 

I'm unable to reproduce the problem, please see https://github.com/Anorov/cloudflare-scrape/issues/264 for a possible workaround.

You might also try setting only a couple of [ciphers](https://www.openssl.org/docs/man1.1.1/man1/ciphers.html) to avoid the CAPTCHA:
```py
import cfscrape
# One TLS v1.3 cipher and one TLS v1.2 cipher
cfscrape.DEFAULT_CIPHERS = 'TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-AES256-SHA384'

scraper = cfscraper.create_scraper()
print(scraper.get('https://www.enotes.com/topics/alpha/').text)
```

Otherwise for further assistance, feel free to generate a report with this [script](https://gist.github.com/pro-src/17654ec3f949b0b17bd1a4aa1b4136b9).

*This must be ran from within the cloned cloudflare-scrape repo if you haven't pip installed cfscrape*
```sh
git clone https://gist.github.com/pro-src/17654ec3f949b0b17bd1a4aa1b4136b9 temp
cp temp/report-enotes.py report.py

python2 report.py
python3 report.py
```

**Comment by bajburtskii** [comment] 2019-06-25 12:33
Thanks for the assistance!
Reports:
python2: http://dpaste.com/25M4JBY
python3: http://dpaste.com/07XJZDY

Setting only a couple of ciphers doesnt seem to help
![Selection_002](https://user-images.githubusercontent.com/1996929/60098582-8d9b5c80-975e-11e9-96ba-c25c2b940db0.png)

**Comment by pro-src** [comment] 2019-06-25 12:48
The difference is in the signature algorithms extensions:

> Signature algorithms hash: 94a2ca79b6ef36b1d692cbbfa5641952
<details><summary>Signature algorithms as reported by ssllabs (Mine)</summary>

```py
(u'SHA256/ECDSA',
 u'SHA384/ECDSA',
 u'SHA512/ECDSA',
 u'Ed25519',
 u'Ed448',
 u'Unknown (0x8)/Unknown (0x9)',
 u'Unknown (0x8)/Unknown (0xa)',
 u'Unknown (0x8)/Unknown (0xb)',
 u'RSA_PSS_SHA256',
 u'RSA_PSS_SHA384',
 u'RSA_PSS_SHA512',
 u'SHA256/RSA',
 u'SHA384/RSA',
 u'SHA512/RSA',
 u'SHA224/ECDSA',
 u'SHA224/RSA',
 u'SHA224/DSA',
 u'SHA256/DSA',
 u'SHA384/DSA',
 u'SHA512/DSA')
```
</details>

> Signature algorithms hash: 402014b899136c3fed09cd745dc01355
<details><summary>Signature algorithms as reported by ssllabs (Yours)</summary>

```py
('SHA256/ECDSA',
 'SHA384/ECDSA',
 'SHA512/ECDSA',
 'Ed25519',
 'Ed448',
 'Unknown (0x8)/Unknown (0x9)',
 'Unknown (0x8)/Unknown (0xa)',
 'Unknown (0x8)/Unknown (0xb)',
 'RSA_PSS_SHA256',
 'RSA_PSS_SHA384',
 'RSA_PSS_SHA512',
 'SHA256/RSA',
 'SHA384/RSA',
 'SHA512/RSA',
 'SHA224/ECDSA',
 'SHA1/ECDSA',
 'SHA224/RSA',
 'SHA1/RSA',
 'SHA224/DSA',
 'SHA1/DSA',
 'SHA256/DSA',
 'SHA384/DSA',
 'SHA512/DSA')
```
</details>

Diff:
```py
('SHA1/ECDSA',
 'SHA1/RSA',
 'SHA1/DSA')
```

Unfortunately, I don't know of a way to fix this, only suggestions.
I find it odd that none of the workarounds worked... I would try using a proxy to rule out an IP problem.
Trying upgrading openssl to v1.1.1c

**Comment by pro-src** [comment] 2019-06-25 13:23
Hey @bajburtskii,

I hate to ask the obvious here but based on the title... Do you get a CAPTCHA when visiting the URL in your web browser? cfscrape can't solve CAPTCHA as noted in the README.

Sorry, if that seems like a dumb question but if so, we can close this issue.

**Comment by bajburtskii** [comment] 2019-06-25 13:30
@pro-src 
The script is run on the server so no web browser obviously, but a simple curl requests from the server does return a captcha page. If it's what you are asking about.

**Comment by pro-src** [comment] 2019-06-25 15:16
Basically, I just wanted to rule out the obvious. I don't get a CAPTCHA when using the browser or curl either so let's keep this open.

it's a very valid issue, thanks for raising it.

**Comment by Bloumbs** [comment] 2019-06-25 20:29
@pro-src  I tried my script again after upgrading my OpenSSL from '1.1.1.a' to '1.1.1.c', and got the same captcha result, but after putting the 'DEFAULT_CIPHERS' line you recommended for @bajburtskii, it fixed my captcha issue

```python
# import cfscrape

# One TLS v1.3 cipher and one TLS v1.2 cipher
cfscrape.DEFAULT_CIPHERS = 'TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-AES256-SHA384'

# scraper = cfscrape.create_scraper()
# print(scraper.get('https://www.enotes.com/topics/alpha/').text)
```

**Comment by bajburtskii** [comment] 2019-06-27 09:27
just in case: I've update openssl version to the latest 1.1.1c but it didn't help.
new report is here http://dpaste.com/3TRXAHJ

**Comment by yooyoyo** [comment] 2019-06-28 11:37
I am unable to access "https://www.desidime.com" - it says blocked by Cloudflare. 
Can anyone help regarding this?

**Closed** 2019-07-06 06:08 UTC
Labels: bug

**Comment by alexandresgf** [comment] 2019-09-21 20:10
Any news? Same problem here, using the latest versions of cfscrape and OpenSSL. Still getting the same captcha error, but when the website is accessed through a web browser, there is no captcha even in anonymous mode or ToR.

`# import cfscrape

# One TLS v1.3 cipher and one TLS v1.2 cipher
cfscrape.DEFAULT_CIPHERS = 'TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-AES256-SHA384'

# scraper = cfscrape.create_scraper()
# print(scraper.get('https://www.enotes.com/topics/alpha/').text)`

Tried the same and it didn't work... any other workaround?

Thanks!

**Comment by pro-src** [comment] 2019-09-21 21:27
> when the website is accessed through a web browser, there is no captcha even in anonymous mode or ToR.

I tried the current stable version of both firefox and google-chrome on 3 different clean IPs and got a CAPTCHA for `www.enotes.com/` and `ww.enotes.com/topics/alpha/` every time. (Both HTTP and HTTPS).

Maybe try clearing your browser's history bud.

**Comment by dudztroyer** [comment] 2019-10-10 19:08
If I get the site via CURL it doesn't get to the captcha page, only to the "please wait 5 seconds" page.

If I get the site via python requests module (the same with cfscrape) it goes straight to the captcha page. I've tryied setting user agents, setting some headers but still doesn't help.

I've even updated to python 3.7.3 using OpenSSL 1.1.1c without any change. (On Python 3.7.3 with OpenSSL 1.0.8 it gave me the outdated OpenSSL message, so I updated it and now the outdated message doesn't appear).

Any suggestions?
