### ISSUE TITLE
unexpected keyword argument 'ssl_context'

### ISSUE THREAD

**Issue by eternalfool** [Anorov/cloudflare-scrape#276] opened 2019-07-31 11:08 UTC
Before creating an issue, first upgrade cfscrape with `pip install -U cfscrape` and see if you're still experiencing the problem.

## Version number

Run `pip show cfscrape` and paste the output below:

```
Metadata-Version: 2.1
Name: cfscrape
Version: 2.0.7
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
Home-page: https://github.com/Anorov/cloudflare-scrape
Author: Anorov
Author-email: anorov.vorona@gmail.com
License: UNKNOWN
Location: /Users/admin/workspace/crawler-reloaded/env/lib/python2.7/site-packages
Requires: requests
```

## Code snippet experiencing the issue

```
from cfscrape import get_tokens
from cfscrape import get_tokens

        cloudflare_tokens, __ = get_tokens(
            request.url,
            user_agent=spider.settings.get('USER_AGENT')
        )

```

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

```
  File "/Users/admin/workspace/xxx/vy_crawlers/middlewares/cloudflare_middleware.py", line 38, in process_response
    user_agent=spider.settings.get('USER_AGENT')
  File "/Users/admin/workspace/xxx/env/lib/python2.7/site-packages/cfscrape/__init__.py", line 337, in get_tokens
    resp = scraper.get(url, **kwargs)
  File "/Users/admin/workspace/xxx/env/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/Users/admin/workspace/xxx/env/lib/python2.7/site-packages/cfscrape/__init__.py", line 121, in request
    resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)
  File "/Users/admin/workspace/xxx/env/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/admin/workspace/xxx/env/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/admin/workspace/xxx/env/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Users/admin/workspace/xxx/env/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 548, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/Users/admin/workspace/xxx/env/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 250, in _get_conn
    return conn or self._new_conn()
  File "/Users/admin/workspace/xxx/env/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 770, in _new_conn
    strict=self.strict, **self.conn_kw)
  File "/Users/admin/workspace/xxx/env/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 171, in __init__
    timeout=timeout, **kw)
  File "/Users/admin/workspace/xxx/env/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 119, in __init__
    _HTTPConnection.__init__(self, *args, **kw)
TypeError: __init__() got an unexpected keyword argument 'ssl_context'
```

## URL of the Cloudflare-protected page

Any page

## URL of Pastebin/Gist with HTML source of protected page

Any page

I tried updating PyOpenSSL and openssl on my system

```
pyOpenSSL==19.0.0

```

```
 openssl version -a
LibreSSL 2.6.4
built on: date not available
platform: information not available
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) blowfish(idx)
compiler: information not available
OPENSSLDIR: "/private/etc/ssl"
```

Removing the following lines makes the  code run

```
        if conn.conn_kw.get("ssl_context"):
            conn.conn_kw["ssl_context"].set_ciphers(DEFAULT_CIPHERS)
        else:
            context = create_urllib3_context(ciphers=DEFAULT_CIPHERS)
            conn.conn_kw["ssl_context"] = context

```

**Comment by pro-src** [comment] 2019-08-09 07:54
Hi @eternalfool,

Thanks for opening this issue. I'm guessing that the problem is your system's LibreSSL of which this project has not been tested against. We should add support for it and would gladly accept a PR.

Cheers

**Comment by Anorov** [comment] 2019-08-11 15:48
@eternalfool

A few questions:

* Can you please add the output of `python --version`
* Can you please add the output of `pip show urllib3 requests`
* Could you try using the latest version of Python, [version 3.7.4](https://www.python.org/downloads/), and see if you're still encountering this problem?

**Comment by pro-src** [comment] 2019-08-12 16:57
<details><summary>Oops...</summary>

On second thought, this doesn't likely have anything to do with LibreSSL for a number of reasons. It has been tested against LibreSSL but just not by me, until now. :smile:

Without pyopenssl, cryptography, etc. being installed:
<details><summary>Python 2 - Interactive Session</summary>

```
Python 2.7.16 (413a49145e:413a49145e, Aug 12 2019, 16:20:55) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.OPENSSL_VERSION
'LibreSSL 3.0.0'
>>> import cfscrape
>>> scraper = cfscrape.create_scraper()
>>> scraper.get('https://osbot.org')
<Response [200]>
```
</details>
<details><summary>Python 3 - Interactive Session</summary>

```
Python 3.9.0a0 (heads/master:f9590ed, Aug 12 2019, 15:37:21) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.OPENSSL_VERSION
'LibreSSL 3.0.0'
>>> import cfscrape
>>> scraper = cfscrape.create_scraper()
>>> scraper.get('https://osbot.org')
<Response [200]>
```
</details>

Same results with pyopenssl, cryptography, etc. installed and imported prior to importing cfscrape:
```
>>> import OpenSSL, sys
>>> OpenSSL.__title__ == 'pyOpenSSL'
True
>>> [s for s in sys.modules if 'cryptography' in s]
['cryptography.__about__', 'cryptography', 'cryptography.x509.certificate_transparency', 'cryptography.utils', 'cryptography.hazmat', 'cryptography.hazmat.primitives', 'cryptography.hazmat.primitives.asymmetric', 'cryptography.hazmat.primitives.asymmetric.dsa', 'cryptography.hazmat._oid', 'cryptography.hazmat.primitives.asymmetric.ec', 'cryptography.exceptions', 'cryptography.hazmat.backends', 'cryptography.hazmat.backends.interfaces', 'cryptography.hazmat.primitives.asymmetric.rsa', 'cryptography.hazmat.bindings', 'cryptography.hazmat.bindings._constant_time', 'cryptography.hazmat.primitives.constant_time', 'cryptography.hazmat.primitives.serialization.base', 'cryptography.hazmat.primitives.asymmetric.ed25519', 'cryptography.hazmat.primitives.serialization.ssh', 'cryptography.hazmat.primitives.serialization', 'cryptography.hazmat.primitives.hashes', 'cryptography.x509.oid', 'cryptography.x509.name', 'cryptography.x509.general_name', 'cryptography.x509.extensions', 'cryptography.x509.base', 'cryptography.x509', 'cryptography.hazmat.bindings.openssl', 'cryptography.hazmat.bindings._openssl', 'cryptography.hazmat.bindings.openssl._conditional', 'cryptography.hazmat.bindings.openssl.binding']
```

No problems here!
</details>

**Comment by Anorov** [comment] 2019-08-24 02:20
Closing this for now.

**Closed by Anorov** 2019-08-24 02:20 UTC
Labels: bug, needs: more info, unconfirmed
